<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtqq/1+4u87FSQacMsNBR'."\n".'4YUSzqNc9wUB3I6onGZ1wcsZoJ7ikbnem4Y+yOBtuzE2LaqD6nKGSbX7QcwwtsPa'."\n".'yKNnaYy+Oz3qt6txuFqMWdge5iN+qx+jlyuiglnOSrMHg5S+7HLz4mxl3FMHYkAT'."\n".'/cvoLh65QGP+10Op5h7F+dX1YFsqDr4nyEOBq6KjFDjuJZ56JqUuERA58G1MQYNC'."\n".'tCjOfLN9ipTL052GxqZM0BdjNa83pktq9VQYysSgVuPkCXhE+cgPyxuodfdr6Z0N'."\n".'lo+Z7upSvaFjMBVO7XCCe5xUGDCksuiUlG7RUn2fC39R4YBkq6qzZTIP+h0uZw8J'."\n".'/wIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
