<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6qN2uS\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6qN2uS/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ6qN2uS.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ6qN2uS\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerZ6qN2uS\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Z6qN2uS',
    'container.build_id' => 'c1f17037',
    'container.build_time' => 1696384216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6qN2uS');
